### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by Hrishikesh-Panigrahi** [GauravSamanta/book-store-go#1]
**Line Number:** 27

**Description:** There is a spelling mistake in the CreateBook function. The variable `booker` should be renamed to `newBook` to accurately represent that it holds a book object.

**Current Code:**
``` 
booker := &models.Book{
	Name:        book.Name,
	Description: book.Description,
	Author:      book.Author,
	Tags:        book.Tags,
}
```

**Suggested Fix:** Rename the variable booker to newbook:
```
newbook := &models.Book{
	Name:        book.Name,
	Description: book.Description,
	Author:      book.Author,
	Tags:        book.Tags,
}
```

**Comment by GauravSamanta** [comment]
Kindly open a PR and assist me to solve this mistake☺️
